# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Filipe Guedes
email: fgs.guedes@gmail.com

description: >
  Where I eventually publish stuff

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fgsguedes.com" # the base hostname & protocol for your site

name: 'Filipe Guedes'
bio: >
  Android Developer at 99taxis and Kotlin advocate.
  Addicted to keyboard shortcuts and efficiency.
  Enjoy running, cycling and jugging.
  All opinions are my own.
  Spaces > Tabs, Emacs > Vi

author_image: "/assets/images/author.jpg"
twitter_username: fgsguedes
github_username:  fgsguedes

# Build settings
markdown: kramdown
